export const institutes = [
  {
    id: "D6cPDW222ayuo4XtPFDeT",
    name: "University of Oxford",
    location: {
      longitude: -1.2577,
      latitude: 51.7538,
    },
    department: "Computer Science",
    laboratory_id: "kkeMOKvN2X6UzcGKyUmnR",
  },
  {
    id: "HAwWJToDPSfnbFcxmkfnX",
    name: "University of Cambridge",
    location: {
      longitude: 0.1218,
      latitude: 52.2053,
    },
    department: "Electrical Engineering",
    laboratory_id: "1ajRoZROFrmaY52HlAwxk",
  },
  {
    id: "UWkhBbVRWUS1V39OjThS4",
    name: "University of Manchester",
    location: {
      longitude: -2.2361,
      latitude: 53.4636,
    },
    department: "Mechanical Engineering",
    laboratory_id: "JeGuBnwE8uvThwQKqtiov",
  },
  {
    id: "r7dDbdpwtUlOsx78pNqtD",
    name: "University of Edinburgh",
    location: {
      longitude: -3.1883,
      latitude: 55.9474,
    },
    department: "Civil Engineering",
    laboratory_id: "YrevEeLSLqvSdwGuiaj4w",
  },
  {
    id: "BZhnIXKLxZCYcF9HD0nND",
    name: "University of Bristol",
    location: {
      longitude: -2.5972,
      latitude: 51.4545,
    },
    department: "Aerospace Engineering",
    laboratory_id: "WYanLL7J7nNMfT9Ir5325",
  },
  {
    id: "T0VHYVFhRyI9iYug1Sadv",
    name: "University of Leeds",
    location: {
      longitude: -1.5462,
      latitude: 53.7944,
    },
    department: "Chemical Engineering",
    laboratory_id: "ADCF9DE57xkjUzFoiRvUE",
  },
  {
    id: "oRQuX9j2NQJKDyeKQEK3P",
    name: "University of Sheffield",
    location: {
      longitude: -1.4889,
      latitude: 53.3829,
    },
    department: "Biomedical Engineering",
    laboratory_id: "WYjbueHx3v3gJ0NQvWFfH",
  },
  {
    id: "OLirUIdTFEaSTZg1BVRLn",
    name: "University of Liverpool",
    location: {
      longitude: -2.9684,
      latitude: 53.4051,
    },
    department: "Environmental Engineering",
    laboratory_id: "hR8Yj3DzV4ISjIfWvluLH",
  },
  {
    id: "g2ZyczxPUSAIw5GsUImIz",
    name: "University of Newcastle",
    location: {
      longitude: -1.6233,
      latitude: 54.9771,
    },
    department: "Geological Engineering",
    laboratory_id: "LDJ79NBTwUHKRHPgR7A9r",
  },
  {
    id: "47G17HdJACCCVZLPK9MpY",
    name: "University of Nottingham",
    location: {
      longitude: -1.1777,
      latitude: 52.9543,
    },
    department: "Nanotechnology",
    laboratory_id: "YL6IBKOxN8CYgIJBwaMIV",
  },
];

export const laboratories = [
  {
    id: "kkeMOKvN2X6UzcGKyUmnR",
    name: "Robotics Laboratory",
    department: "Computer Science",
    description:
      "The Robotics Laboratory is a state-of-the-art facility for research and development in robotics and autonomous systems.",
    equipment: "Robotics equipment, 3D printers",
    tags: ["robotics", "autonomous systems", "artificial intelligence"],
    institute_id: "D6cPDW222ayuo4XtPFDeT",
    organisation_id: "m6fLkIz8ADN8xUnyKjx0S",
    project_ids: [
      "UShJSD15BmhAmjfvEuwoL",
      "dIjamS88zRGy9VsuGnGGO",
      "s52bDM23QRKbc7VpHasqZ",
      "9IBxp6FXuuUzKuuNXa2BW",
      "hz6iSBHK1E9wzp7VH84hr",
    ],
  },
  {
    id: "1ajRoZROFrmaY52HlAwxk",
    name: "Electronics Laboratory",
    department: "Electrical Engineering",
    description:
      "The Electronics Laboratory is a well-equipped facility for research and development in electronics and photonics.",
    equipment: "Electronics equipment, oscilloscopes",
    tags: ["electronics", "photonics", "optoelectronics"],
    institute_id: "HAwWJToDPSfnbFcxmkfnX",
    organisation_id: "gvCZCMQUOM2Fhzvr9QV6v",
    project_ids: ["WIOe2iyIcqmmnmbU7o4OI", "s8P7N3hnSgn1wciVrJcZX"],
  },
  {
    id: "JeGuBnwE8uvThwQKqtiov",
    name: "Materials Laboratory",
    department: "Mechanical Engineering",
    description:
      "The Materials Laboratory is a state-of-the-art facility for research and development in materials science and engineering.",
    equipment: "Materials testing equipment, microscopes",
    tags: ["materials science", "materials engineering", "nanotechnology"],
    institute_id: "UWkhBbVRWUS1V39OjThS4",
    organisation_id: "yCrDdpnz4EMOAmuS28HUo",
    project_ids: ["WH5xJlk3NctZ0HTMbu8O0"],
  },
  {
    id: "YrevEeLSLqvSdwGuiaj4w",
    name: "Computational Fluid Dynamics Laboratory",
    department: "Civil Engineering",
    description:
      "The Computational Fluid Dynamics Laboratory is a well-equipped facility for research and development in computational fluid dynamics.",
    equipment: "Computational fluid dynamics software, wind tunnels",
    tags: ["computational fluid dynamics", "fluid mechanics", "aerodynamics"],
    institute_id: "r7dDbdpwtUlOsx78pNqtD",
    organisation_id: "xkVgmegOy3IHWUnZW3g75",
    project_ids: ["Lq5uCtJZYFBod2jOf8bkY"],
  },
  {
    id: "WYanLL7J7nNMfT9Ir5325",
    name: "Aerospace Laboratory",
    department: "Aerospace Engineering",
    description:
      "The Aerospace Laboratory is a state-of-the-art facility for research and development in aerospace engineering.",
    equipment: "Aerospace equipment, wind tunnels",
    tags: ["aerospace engineering", "space exploration", "rocketry"],
    institute_id: "BZhnIXKLxZCYcF9HD0nND",
    organisation_id: "1NyP1onI3dZPbupJmA1at",
    project_ids: [
      "QnJ4dtDhB7OC3Q35dTlZa",
      "taUGiuiZTF504ll664mfK",
      "Lk3Te5AnjgHfESyVzFbnO",
    ],
  },
  {
    id: "ADCF9DE57xkjUzFoiRvUE",
    name: "Chemical Engineering Laboratory",
    department: "Chemical Engineering",
    description:
      "The Chemical Engineering Laboratory is a well-equipped facility for research and development in chemical engineering.",
    equipment: "Chemical engineering equipment, reaction vessels",
    tags: ["chemical engineering", "process control", "reaction kinetics"],
    institute_id: "T0VHYVFhRyI9iYug1Sadv",
    organisation_id: "nOoPycStiaiRMXC1ZjoDA",
    project_ids: [],
  },
  {
    id: "WYjbueHx3v3gJ0NQvWFfH",
    name: "Biomedical Engineering Laboratory",
    department: "Biomedical Engineering",
    description:
      "The Biomedical Engineering Laboratory is a state-of-the-art facility for research and development in biomedical engineering.",
    equipment: "Biomedical engineering equipment, microscopes",
    tags: ["biomedical engineering", "medical devices", "biomechanics"],
    institute_id: "oRQuX9j2NQJKDyeKQEK3P",
    organisation_id: "VC31IPvFsTNinxDQCrf8E",
    project_ids: [
      "jGnWtT5aASgxLztrefMbu",
      "cqo6521E5JH8FsR4bvH6V",
      "hGOmH0Yd8UgnqQmcggXuD",
      "FUtPBrWuBVe8HtTLOba99",
      "fpWh9JYY9lsdBKvUSDhlj",
    ],
  },
  {
    id: "hR8Yj3DzV4ISjIfWvluLH",
    name: "Environmental Engineering Laboratory",
    department: "Environmental Engineering",
    description:
      "The Environmental Engineering Laboratory is a well-equipped facility for research and development in environmental engineering.",
    equipment:
      "Environmental engineering equipment, water quality testing equipment",
    tags: ["environmental engineering", "water resources", "air pollution"],
    institute_id: "OLirUIdTFEaSTZg1BVRLn",
    organisation_id: "mHAqDYS3RfDpmwosZQzD4",
    project_ids: [
      "FjlLzhqBdWooxgA8thklM",
      "1dwRWRt2AaRayScd6yJtN",
      "iWS6jBGrZdTKpzc1qfGId",
      "FYnjzATFuWGfeFDT79Rh7",
      "9xdVVTCgFXKvJRNspFIro",
      "fINamySQ54D1heKLVOEA3",
    ],
  },
  {
    id: "LDJ79NBTwUHKRHPgR7A9r",
    name: "Geological Engineering Laboratory",
    department: "Geological Engineering",
    description:
      "The Geological Engineering Laboratory is a state-of-the-art facility for research and development in geological engineering.",
    equipment: "Geological engineering equipment, rock testing equipment",
    tags: ["geological engineering", "geology", "petroleum engineering"],
    institute_id: "g2ZyczxPUSAIw5GsUImIz",
    organisation_id: "heORH6m2ALRTQEGLu5RLN",
    project_ids: [
      "g7qdBfk1xOMY5FcrSAyXm",
      "tiLzRA1Vh0ZGyBvpI9P3A",
      "40icrq32R8gQxfyxg7EEg",
    ],
  },
  {
    id: "YL6IBKOxN8CYgIJBwaMIV",
    name: "Nanotechnology Laboratory",
    department: "Nanotechnology",
    description:
      "The Nanotechnology Laboratory is a well-equipped facility for research and development in nanotechnology.",
    equipment: "Nanotechnology equipment, scanning electron microscopes",
    tags: ["nanotechnology", "nanoscience", "nanomaterials"],
    institute_id: "47G17HdJACCCVZLPK9MpY",
    organisation_id: "MoO1TtRpCotkyKVELuLb4",
    project_ids: [
      "nwMxtOXBrBTVrsXYG0Y8t",
      "6OZfGXC2gQyl9E6Cg74Dc",
      "0UTtAikQ4PJeWZUZujc82",
    ],
  },
];

export const organisations = [
  {
    id: "m6fLkIz8ADN8xUnyKjx0S",
    name: "Computer Science Research Council",
    description: "Funds research in computer science and related fields",
    address: "10-11 Carlton House Terrace, London, SW1Y 5AH",
    laboratory_id: "kkeMOKvN2X6UzcGKyUmnR",
    project_ids: [
      "UShJSD15BmhAmjfvEuwoL",
      "dIjamS88zRGy9VsuGnGGO",
      "s52bDM23QRKbc7VpHasqZ",
      "hz6iSBHK1E9wzp7VH84hr",
    ],
  },
  {
    id: "gvCZCMQUOM2Fhzvr9QV6v",
    name: "Electrical Engineering Society",
    description: "Supports research and development in electrical engineering",
    address: "20-21 Bedford Square, London, WC1B 3HH",
    laboratory_id: "WYjbueHx3v3gJ0NQvWFfH",
    project_ids: ["WIOe2iyIcqmmnmbU7o4OI", "s8P7N3hnSgn1wciVrJcZX"],
  },
  {
    id: "yCrDdpnz4EMOAmuS28HUo",
    name: "Mechanical Engineering Research Institute",
    description: "Funds research in mechanical engineering and related fields",
    address: "22-24 George Square, Edinburgh, EH8 9LD",
    laboratory_id: "JeGuBnwE8uvThwQKqtiov",
    project_ids: ["WH5xJlk3NctZ0HTMbu8O0", "9IBxp6FXuuUzKuuNXa2BW"],
  },
  {
    id: "xkVgmegOy3IHWUnZW3g75",
    name: "Civil Engineering Association",
    description: "Supports research and development in civil engineering",
    address: "25-27 Great George Street, London, SW1P 3AA",
    laboratory_id: "YrevEeLSLqvSdwGuiaj4w",
    project_ids: ["Lq5uCtJZYFBod2jOf8bkY"],
  },
  {
    id: "1NyP1onI3dZPbupJmA1at",
    name: "Aerospace Engineering Research Council",
    description: "Funds research in aerospace engineering and related fields",
    address: "30-32 Oxford Street, Cambridge, CB1 1DW",
    laboratory_id: "WYanLL7J7nNMfT9Ir5325",
    project_ids: [
      "QnJ4dtDhB7OC3Q35dTlZa",
      "taUGiuiZTF504ll664mfK",
      "bDhf5pLI01ZzttUtocin1",
    ],
  },
  {
    id: "nOoPycStiaiRMXC1ZjoDA",
    name: "Chemical Engineering Research Institute",
    description: "Funds research in chemical engineering and related fields",
    address: "33-35 University Road, Birmingham, B15 2TT",
    laboratory_id: "ADCF9DE57xkjUzFoiRvUE",
    project_ids: [],
  },
  {
    id: "VC31IPvFsTNinxDQCrf8E",
    name: "Biomedical Engineering Society",
    description: "Supports research and development in biomedical engineering",
    address: "40-42 Guildford Street, London, WC1N 2BP",
    laboratory_id: "WYjbueHx3v3gJ0NQvWFfH",
    project_ids: [
      "jGnWtT5aASgxLztrefMbu",
      "cqo6521E5JH8FsR4bvH6V",
      "hGOmH0Yd8UgnqQmcggXuD",
      "FUtPBrWuBVe8HtTLOba99",
      "fpWh9JYY9lsdBKvUSDhlj",
    ],
  },
  {
    id: "mHAqDYS3RfDpmwosZQzD4",
    name: "Environmental Engineering Research Council",
    description:
      "Funds research in environmental engineering and related fields",
    address: "45-47 St Andrew's Street, Cambridge, CB2 3BU",
    laboratory_id: "hR8Yj3DzV4ISjIfWvluLH",
    project_ids: [
      "FjlLzhqBdWooxgA8thklM",
      "1dwRWRt2AaRayScd6yJtN",
      "iWS6jBGrZdTKpzc1qfGId",
      "FYnjzATFuWGfeFDT79Rh7",
      "9xdVVTCgFXKvJRNspFIro",
      "fINamySQ54D1heKLVOEA3",
    ],
  },
  {
    id: "heORH6m2ALRTQEGLu5RLN",
    name: "Geological Engineering Research Institute",
    description: "Funds research in geological engineering and related fields",
    address: "50-52 University Road, Cardiff, CF10 3AT",
    laboratory_id: "LDJ79NBTwUHKRHPgR7A9r",
    project_ids: [
      "g7qdBfk1xOMY5FcrSAyXm",
      "tiLzRA1Vh0ZGyBvpI9P3A",
      "40icrq32R8gQxfyxg7EEg",
    ],
  },
  {
    id: "MoO1TtRpCotkyKVELuLb4",
    name: "Nanotechnology Research Council",
    description: "Funds research in nanotechnology and related fields",
    address: "55-57 South Road, Durham, DH1 3LG",
    laboratory_id: "YL6IBKOxN8CYgIJBwaMIV",
    project_ids: [
      "nwMxtOXBrBTVrsXYG0Y8t",
      "6OZfGXC2gQyl9E6Cg74Dc",
      "0UTtAikQ4PJeWZUZujc82",
    ],
  },
];

export const projects = [
  {
    id: "UShJSD15BmhAmjfvEuwoL",
    name: "Autonomous Robotics for Environmental Monitoring",
    started_date: "2020-01-01",
    finished_date: "2022-01-01",
    goals: "Develop an autonomous robotics system for environmental monitoring",
    successful: true,
    laboratory_id: "kkeMOKvN2X6UzcGKyUmnR",
    organisation_id: "m6fLkIz8ADN8xUnyKjx0S",
  },
  {
    id: "jGnWtT5aASgxLztrefMbu",
    name: "Advanced Electronics for Medical Devices",
    started_date: "2020-06-01",
    finished_date: null,
    goals: "Develop advanced electronics for medical devices",
    successful: null,
    laboratory_id: "WYjbueHx3v3gJ0NQvWFfH",
    organisation_id: "VC31IPvFsTNinxDQCrf8E",
  },
  {
    id: "nwMxtOXBrBTVrsXYG0Y8t",
    name: "Nanotechnology for Energy Applications",
    started_date: "2019-01-01",
    finished_date: "2021-01-01",
    goals: "Develop nanotechnology for energy applications",
    successful: true,
    laboratory_id: "YL6IBKOxN8CYgIJBwaMIV",
    organisation_id: "MoO1TtRpCotkyKVELuLb4",
  },
  {
    id: "Lq5uCtJZYFBod2jOf8bkY",
    name: "Computational Fluid Dynamics for Aerospace Applications",
    started_date: "2018-01-01",
    finished_date: "2020-01-01",
    goals: "Develop computational fluid dynamics for aerospace applications",
    successful: true,
    laboratory_id: "YrevEeLSLqvSdwGuiaj4w",
    organisation_id: "xkVgmegOy3IHWUnZW3g75",
  },
  {
    id: "QnJ4dtDhB7OC3Q35dTlZa",
    name: "Aerospace Engineering and Systems for Space Exploration",
    started_date: "2020-01-01",
    finished_date: null,
    goals: "Develop aerospace engineering and systems for space exploration",
    successful: null,
    laboratory_id: "WYanLL7J7nNMfT9Ir5325",
    organisation_id: "1NyP1onI3dZPbupJmA1at",
  },
  {
    id: "cqo6521E5JH8FsR4bvH6V",
    name: "Biomedical Engineering for Tissue Engineering",
    started_date: "2019-06-01",
    finished_date: "2022-06-01",
    goals: "Develop biomedical engineering for tissue engineering",
    successful: true,
    laboratory_id: "WYjbueHx3v3gJ0NQvWFfH",
    organisation_id: "VC31IPvFsTNinxDQCrf8E",
  },
  {
    id: "FjlLzhqBdWooxgA8thklM",
    name: "Environmental Engineering for Water Resources Management",
    started_date: "2018-06-01",
    finished_date: "2021-06-01",
    goals: "Develop environmental engineering for water resources management",
    successful: true,
    laboratory_id: "hR8Yj3DzV4ISjIfWvluLH",
    organisation_id: "mHAqDYS3RfDpmwosZQzD4",
  },
  {
    id: "g7qdBfk1xOMY5FcrSAyXm",
    name: "Geological Engineering for Geothermal Energy",
    started_date: "2020-01-01",
    finished_date: null,
    goals: "Develop geological engineering for geothermal energy",
    successful: null,
    laboratory_id: "LDJ79NBTwUHKRHPgR7A9r",
    organisation_id: "heORH6m2ALRTQEGLu5RLN",
  },
  {
    id: "6OZfGXC2gQyl9E6Cg74Dc",
    name: "Nanotechnology for Quantum Computing",
    started_date: "2019-01-01",
    finished_date: "2022-01-01",
    goals: "Develop nanotechnology for quantum computing",
    successful: true,
    laboratory_id: "YL6IBKOxN8CYgIJBwaMIV",
    organisation_id: "MoO1TtRpCotkyKVELuLb4",
  },
  {
    id: "dIjamS88zRGy9VsuGnGGO",
    name: "Robotics and Autonomous Systems for Manufacturing",
    started_date: "2020-06-01",
    finished_date: null,
    goals: "Develop robotics and autonomous systems for manufacturing",
    successful: null,
    laboratory_id: "kkeMOKvN2X6UzcGKyUmnR",
    organisation_id: "m6fLkIz8ADN8xUnyKjx0S",
  },
  {
    id: "WH5xJlk3NctZ0HTMbu8O0",
    name: "Advanced Materials for Energy Storage",
    started_date: "2020-01-01",
    finished_date: null,
    goals: "Develop advanced materials for energy storage",
    successful: null,
    laboratory_id: "JeGuBnwE8uvThwQKqtiov",
    organisation_id: "yCrDdpnz4EMOAmuS28HUo",
  },
  {
    id: "hGOmH0Yd8UgnqQmcggXuD",
    name: "Biomechanical Engineering for Medical Devices",
    started_date: "2019-06-01",
    finished_date: "2022-06-01",
    goals: "Develop biomechanical engineering for medical devices",
    successful: true,
    laboratory_id: "WYjbueHx3v3gJ0NQvWFfH",
    organisation_id: "VC31IPvFsTNinxDQCrf8E",
  },
  {
    id: "FUtPBrWuBVe8HtTLOba99",
    name: "Computational Biology for Disease Modeling",
    started_date: "2018-01-01",
    finished_date: "2021-01-01",
    goals: "Develop computational biology for disease modeling",
    successful: true,
    laboratory_id: "WYjbueHx3v3gJ0NQvWFfH",
    organisation_id: "VC31IPvFsTNinxDQCrf8E",
  },
  {
    id: "s52bDM23QRKbc7VpHasqZ",
    name: "Data Science for Business Intelligence",
    started_date: "2020-06-01",
    finished_date: null,
    goals: "Develop data science for business intelligence",
    successful: null,
    laboratory_id: "kkeMOKvN2X6UzcGKyUmnR",
    organisation_id: "m6fLkIz8ADN8xUnyKjx0S",
  },
  {
    id: "WIOe2iyIcqmmnmbU7o4OI",
    name: "Electrical Engineering for Renewable Energy",
    started_date: "2019-01-01",
    finished_date: "2022-01-01",
    goals: "Develop electrical engineering for renewable energy",
    successful: true,
    laboratory_id: "1ajRoZROFrmaY52HlAwxk",
    organisation_id: "gvCZCMQUOM2Fhzvr9QV6v",
  },
  {
    id: "1dwRWRt2AaRayScd6yJtN",
    name: "Environmental Engineering for Air Quality Management",
    started_date: "2018-06-01",
    finished_date: "2021-06-01",
    goals: "Develop environmental engineering for air quality management",
    successful: true,
    laboratory_id: "hR8Yj3DzV4ISjIfWvluLH",
    organisation_id: "mHAqDYS3RfDpmwosZQzD4",
  },
  {
    id: "tiLzRA1Vh0ZGyBvpI9P3A",
    name: "Geological Engineering for Mining Operations",
    started_date: "2020-01-01",
    finished_date: null,
    goals: "Develop geological engineering for mining operations",
    successful: null,
    laboratory_id: "LDJ79NBTwUHKRHPgR7A9r",
    organisation_id: "heORH6m2ALRTQEGLu5RLN",
  },
  {
    id: "taUGiuiZTF504ll664mfK",
    name: "Materials Science for Aerospace Applications",
    started_date: "2019-06-01",
    finished_date: "2022-06-01",
    goals: "Develop materials science for aerospace applications",
    successful: true,
    laboratory_id: "WYanLL7J7nNMfT9Ir5325",
    organisation_id: "1NyP1onI3dZPbupJmA1at",
  },
  {
    id: "9IBxp6FXuuUzKuuNXa2BW",
    name: "Mechanical Engineering for Robotics",
    started_date: "2018-01-01",
    finished_date: "2021-01-01",
    goals: "Develop mechanical engineering for robotics",
    successful: true,
    laboratory_id: "kkeMOKvN2X6UzcGKyUmnR",
    organisation_id: "yCrDdpnz4EMOAmuS28HUo",
  },
  {
    id: "0UTtAikQ4PJeWZUZujc82",
    name: "Nanotechnology for Water Purification",
    started_date: "2020-06-01",
    finished_date: null,
    goals: "Develop nanotechnology for water purification",
    successful: null,
    laboratory_id: "YL6IBKOxN8CYgIJBwaMIV",
    organisation_id: "MoO1TtRpCotkyKVELuLb4",
  },
  {
    id: "iWS6jBGrZdTKpzc1qfGId",
    name: "Smart Grid Optimization for Renewable Energy Integration",
    started_date: "2020-01-01",
    finished_date: null,
    goals:
      "Develop advanced algorithms for smart grid optimization to integrate renewable energy sources into the grid",
    successful: null,
    laboratory_id: "hR8Yj3DzV4ISjIfWvluLH",
    organisation_id: "mHAqDYS3RfDpmwosZQzD4",
  },
  {
    id: "fpWh9JYY9lsdBKvUSDhlj",
    name: "Personalized Medicine for Cancer Treatment",
    started_date: "2019-06-01",
    finished_date: "2022-06-01",
    goals:
      "Develop personalized medicine approaches for cancer treatment using genomics and machine learning",
    successful: true,
    laboratory_id: "WYjbueHx3v3gJ0NQvWFfH",
    organisation_id: "VC31IPvFsTNinxDQCrf8E",
  },
  {
    id: "FYnjzATFuWGfeFDT79Rh7",
    name: "Advanced Wind Turbine Design for Increased Efficiency",
    started_date: "2018-01-01",
    finished_date: "2021-01-01",
    goals:
      "Develop advanced wind turbine designs using computational fluid dynamics and machine learning",
    successful: true,
    laboratory_id: "hR8Yj3DzV4ISjIfWvluLH",
    organisation_id: "mHAqDYS3RfDpmwosZQzD4",
  },
  {
    id: "hz6iSBHK1E9wzp7VH84hr",
    name: "Data-Driven Decision Making for Supply Chain Optimization",
    started_date: "2020-06-01",
    finished_date: null,
    goals:
      "Develop data-driven decision making approaches for supply chain optimization using machine learning and data analytics",
    successful: null,
    laboratory_id: "kkeMOKvN2X6UzcGKyUmnR",
    organisation_id: "m6fLkIz8ADN8xUnyKjx0S",
  },
  {
    id: "s8P7N3hnSgn1wciVrJcZX",
    name: "Electric Vehicle Charging Infrastructure Development",
    started_date: "2019-01-01",
    finished_date: "2022-01-01",
    goals:
      "Develop electric vehicle charging infrastructure using advanced power electronics and energy storage systems",
    successful: true,
    laboratory_id: "1ajRoZROFrmaY52HlAwxk",
    organisation_id: "gvCZCMQUOM2Fhzvr9QV6v",
  },
  {
    id: "9xdVVTCgFXKvJRNspFIro",
    name: "Water Treatment Technologies for Rural Communities",
    started_date: "2018-06-01",
    finished_date: "2021-06-01",
    goals:
      "Develop water treatment technologies for rural communities using low-cost and sustainable approaches",
    successful: true,
    laboratory_id: "hR8Yj3DzV4ISjIfWvluLH",
    organisation_id: "mHAqDYS3RfDpmwosZQzD4",
  },
  {
    id: "40icrq32R8gQxfyxg7EEg",
    name: "Geothermal Energy Exploration and Development",
    started_date: "2020-01-01",
    finished_date: null,
    goals:
      "Develop geothermal energy exploration and development approaches using advanced geophysical and geochemical techniques",
    successful: null,
    laboratory_id: "LDJ79NBTwUHKRHPgR7A9r",
    organisation_id: "heORH6m2ALRTQEGLu5RLN",
  },
  {
    id: "bDhf5pLI01ZzttUtocin1",
    name: "Advanced Materials for Aerospace Applications",
    started_date: "2019-06-01",
    finished_date: "2022-06-01",
    goals:
      "Develop advanced materials for aerospace applications using nanotechnology and composite materials",
    successful: true,
    laboratory_id: "WYanLL7J7nNMfT9Ir5325",
    organisation_id: "1NyP1onI3dZPbupJmA1at",
  },
  {
    id: "Lk3Te5AnjgHfESyVzFbnO",
    name: "Robotics and Autonomous Systems for Manufacturing",
    started_date: "2018-01-01",
    finished_date: "2021-01-01",
    goals:
      "Develop robotics and autonomous systems for manufacturing using machine learning and computer vision",
    successful: true,
    laboratory_id: "JeGuBnwE8uvThwQKqtiov",
    organisation_id: "yCrDdpnz4EMOAmuS28HUo",
  },
  {
    id: "fINamySQ54D1heKLVOEA3",
    name: "Sustainable Energy Storage Systems for Grid-Scale Applications",
    started_date: "2020-06-01",
    finished_date: null,
    goals:
      "Develop sustainable energy storage systems for grid-scale applications using advanced battery technologies and power electronics",
    successful: null,
    laboratory_id: "hR8Yj3DzV4ISjIfWvluLH",
    organisation_id: "mHAqDYS3RfDpmwosZQzD4",
  },
];
